ClassAttendance/src/WebUI/Models/ViewModels/GroupModel/GroupViewModel.cs
using BLL.Models;
using System.Collections.Generic;

namespace WebUI.Models.ViewModels.GroupModel
{
    public class GroupViewModel
    {
        public Group Group { get; set; }

        public List<Student> Students { get; set; }
    }
}

ClassAttendance/src/WebUI/Controllers/GroupsController.cs
using BLL.Exceptions;
using BLL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using WebUI.Extensions;
using WebUI.Facades;
using WebUI.Identity;
using WebUI.Models;

namespace WebUI.Controllers
{
    [Authorize(Roles = Roles.Manager)]
    public class GroupsController : Controller
    {
        private readonly GroupsFacade _groupFacade;
        private readonly ILogger<GroupsController> _logger;

        public GroupsController(GroupsFacade groupFacade, ILogger<GroupsController> logger)
        {
            _groupFacade = groupFacade;
            _logger = logger;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var models = await _groupFacade.GetGroupViewModelsAsync();
            _logger.LogInformation("Fetched groups");

            return View(models);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var lecturer = new Group();

            return View(lecturer);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Add(Group group)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _groupFacade.AddGroupAsync(group);

                    return RedirectToAction(nameof(List));
                }
                catch (BusinessLogicException ex)
                {
                    _logger.LogError(ex.Message);
                    var error = new ErrorViewModel
                    {
                        ErrorMessage = ex.Message,
                        ReturnUrl = Request.GetReferer(),
                    };

                    return View("Error", error);
                }  
            }

            return View(group);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var lecturer = await _groupFacade.GetByIdAsync(id);

            return View(lecturer);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(Group group)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _groupFacade.UpdateGroupAsync(group);

                    return RedirectToAction(nameof(List));
                }
                catch (BusinessLogicException ex)
                {
                    _logger.LogError(ex.Message);
                    var error = new ErrorViewModel
                    {
                        ErrorMessage = ex.Message,
                        ReturnUrl = Request.GetReferer(),
                    };

                    return View("Error", error);
                }
            }

            return View(group);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _groupFacade.DeleteGroupAsync(id);

                return RedirectToAction(nameof(List));
            }
            catch (BusinessLogicException ex)
            {
                _logger.LogError(ex.Message);
                var error = new ErrorViewModel
                {
                    ErrorMessage = ex.Message,
                    ReturnUrl = Request.GetReferer(),
                };

                return View("Error", error);
            }
        }
    }
}

ClassAttendance/src/WebUI/Views/Groups/Add.cshtml
@using BLL.Models
@model Group

<form asp-action="Add" asp-controller="Groups" asp-antiforgery="true">
    <div>
        <div>
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" />
        </div>
    </div>
    <button type="submit">
        Save
    </button>
</form>

ClassAttendance/src/WebUI/Views/Groups/List.cshtml
@using WebUI.Models.ViewModels.GroupModel;
@model IEnumerable<GroupViewModel>

@foreach (var group in Model)
{
    @await Html.PartialAsync("_Group", group)
}

ClassAttendance/src/WebUI/Views/Groups/Update.cshtml
@using BLL.Models
@model Group

<form asp-action="Update" asp-controller="Groups" asp-antiforgery="true">
    <div>
        <input type="hidden" asp-for="Id" />
        <div>
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" />
        </div>
    </div>
    <button type="submit">
        Save
    </button>
</form>

ClassAttendance/src/WebUI/Views/Groups/_Group.cshtml
@using WebUI.Models.ViewModels.GroupModel
@model GroupViewModel
@{ 
    var hasStudents = Model.Students.Any();
}

<div class="card card-body bg-dark my-auto text-light" style="width: 60%">
    <h3>@Model.Group.Name</h3>
    @if (hasStudents)
    {
        <h3>Students:</h3>
        @foreach (var student in Model.Students)
        {
           <h4>@($"{student.FirstName} {student.LastName}")</h4>
        }
    }
    

    <form asp-action="Update" asp-controller="Groups" asp-route-id="@Model.Group.Id" method="get">
        <button type="submit" class="btn btn-success">
            Update group
        </button>
    </form>

    <form asp-action="Delete" asp-controller="Groups" asp-route-id="@Model.Group.Id" method="get">
        <button type="submit" class="btn btn-danger">
            Delete group
        </button>
    </form>

</div>