ClassAttendance/src/WebUI/Controllers/LecturersController.cs
using BLL.Exceptions;
using BLL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using WebUI.Extensions;
using WebUI.Facades;
using WebUI.Identity;
using WebUI.Models;

namespace WebUI.Controllers
{
    [Authorize(Roles = Roles.Manager)]
    public class LecturersController : Controller
    {
        private readonly LecturersFacade _lecturersFacade;
        private readonly ILogger<LecturersController> _logger;

        public LecturersController(LecturersFacade lecturersFacade, ILogger<LecturersController> logger)
        {
            _lecturersFacade = lecturersFacade;
            _logger = logger;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var models = await _lecturersFacade.GetLecturers();
            _logger.LogInformation("Fetched lecturers");

            return View(models);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var lecturer = new Lecturer();

            return View(lecturer);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Add(Lecturer lecturer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _lecturersFacade.AddLecturerAsync(lecturer);
                    _logger.LogInformation("Added new lecturer");

                    return RedirectToAction(nameof(List));
                }
                catch (BusinessLogicException ex)
                {
                    _logger.LogError(ex.Message);
                    var error = new ErrorViewModel
                    {
                        ErrorMessage = ex.Message,
                        ReturnUrl = Request.GetReferer(),
                    };

                    return View("Error", error);
                }
            }

            return View(lecturer);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var lecturer = await _lecturersFacade.GetByIdAsync(id);

            return View(lecturer);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(Lecturer lecturer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _lecturersFacade.UpdateLecturerAsync(lecturer);
                    _logger.LogInformation("Updated lecturer");

                    return RedirectToAction(nameof(List));
                }
                catch (BusinessLogicException ex)
                {
                    _logger.LogError(ex.Message);
                    var error = new ErrorViewModel
                    {
                        ErrorMessage = ex.Message,
                        ReturnUrl = Request.GetReferer(),
                    };

                    return View("Error", error);
                }
            }

            return View(lecturer);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _lecturersFacade.DeleteLecturerAsync(id);
                _logger.LogInformation("Deleted lecturer");
                return RedirectToAction(nameof(List));
            }
            catch (BusinessLogicException ex)
            {
                _logger.LogError(ex.Message);
                var error = new ErrorViewModel
                {
                    ErrorMessage = ex.Message,
                    ReturnUrl = Request.GetReferer(),
                };

                return View("Error", error);
            }
        }
    }
}

ClassAttendance/src/WebUI/Controllers/MissedClassesController.cs
using BLL.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WebUI.Models.ViewModels.MissedClass;
using WebUI.Facades;
using WebUI.Models;
using Microsoft.Extensions.Logging;
using BLL.Exceptions;
using Microsoft.AspNetCore.Authorization;
using WebUI.Identity;
using WebUI.Extensions;

namespace WebUI.Controllers
{
    [Authorize(Roles = Roles.Manager)]
    public class MissedClassesController : Controller
    {
        private readonly MissedClassesFacade _missedClassesFacade;
        private readonly ILogger<MissedClassesController> _logger;

        public MissedClassesController(MissedClassesFacade missedClassesFacade, ILogger<MissedClassesController> logger)
        {
            _missedClassesFacade = missedClassesFacade;
            _logger = logger;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var models = await _missedClassesFacade.GetMissedLecturesAsync();
            _logger.LogInformation("Fetched lecturers");

            return View(models);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var lecturer = await _missedClassesFacade.GetManageViewModelAsync();

            return View(lecturer);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Add(MissedClassManageViewModel model)
        {
            if (ModelState.IsValid)
            {
                var missedClass = new MissedClass
                {
                    ClassId = model.ClassId,
                    StudentId = model.StudentId,
                };

                try
                {
                    await _missedClassesFacade.AddAsync(missedClass);
                    _logger.LogInformation("Added new missed class");

                    return RedirectToAction(nameof(List));

                }
                catch (BusinessLogicException ex)
                {
                    _logger.LogError(ex.Message);
                    var error = new ErrorViewModel
                    {
                        ErrorMessage = ex.Message,
                        ReturnUrl = Request.GetReferer(),
                    };

                    return View("Error", error);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var item = await _missedClassesFacade.GetManageViewModelAsync(id);

            return View(item);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(MissedClassManageViewModel model)
        {
            if (ModelState.IsValid)
            {
                var missedClass = new MissedClass
                {
                    ClassId = model.ClassId,
                    StudentId = model.StudentId,
                };

                try
                {
                    await _missedClassesFacade.UpdateAsync(missedClass);
                    _logger.LogInformation("Updated missed class");

                    return RedirectToAction(nameof(List));

                }
                catch (BusinessLogicException ex)
                {
                    _logger.LogError(ex.Message);
                    var error = new ErrorViewModel
                    {
                        ErrorMessage = ex.Message,
                        ReturnUrl = Request.GetReferer(),
                    };

                    return View("Error", error);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _missedClassesFacade.DeleteAsync(id);
                _logger.LogInformation("Deleted missed class");

                return RedirectToAction(nameof(List));

            }
            catch (BusinessLogicException ex)
            {
                _logger.LogError(ex.Message);
                var error = new ErrorViewModel
                {
                    ErrorMessage = ex.Message,
                    ReturnUrl = Request.GetReferer(),
                };

                return View("Error", error);
            }
        }

        [Authorize(Roles = Roles.UserAndManager)]
        [HttpGet]
        public async Task<IActionResult> Student(int id)
        {
            try
            {
                var viewModels = await _missedClassesFacade.GetStudentMissedClassesAsync(id);
                _logger.LogInformation("Fetched students's missed classes");

                return View(nameof(List), viewModels);
            }
            catch (BusinessLogicException ex)
            {
                _logger.LogError(ex.Message);
                var error = new ErrorViewModel
                {
                    ErrorMessage = ex.Message,
                    ReturnUrl = Request.GetReferer(),
                };

                return View("Error", error);
            }
        }

        [Authorize(Roles = Roles.UserAndManager)]
        [HttpGet]
        public async Task<IActionResult> Lecturer(int id)
        {
            try
            {
                var viewModels = await _missedClassesFacade.GetLecturerMissedClassesAsync(id);
                _logger.LogInformation("Fetched lecturer's missed classes");

                return View(nameof(List), viewModels);
            }
            catch (BusinessLogicException ex)
            {
                _logger.LogError(ex.Message);
                var error = new ErrorViewModel
                {
                    ErrorMessage = ex.Message,
                    ReturnUrl = Request.GetReferer(),
                };

                return View("Error", error);
            }
        }
    }
}

ClassAttendance/src/WebUI/Views/Lecturers/Add.cshtml
@using BLL.Models
@model Lecturer

<form asp-action="Add" asp-controller="Lecturers" asp-antiforgery="true">
    <div>
        <div>
            <label asp-for="FirstName"></label>
            <input type="text" asp-for="FirstName" />
        </div>
        <div>
            <label asp-for="LastName"></label>
            <input type="text" asp-for="LastName" />
        </div>
        <div>
            <label asp-for="Position"></label>
            <input type="text" asp-for="Position" />
        </div>
        <div>
            <input type="submit" value="Save" />
        </div>
    </div>
</form>

ClassAttendance/src/WebUI/Views/Lecturers/List.cshtml
@using BLL.Models
@model IEnumerable<Lecturer>

@foreach (var lecturer in Model)
{
    @await Html.PartialAsync("_Lecturer", lecturer)
}

ClassAttendance/src/WebUI/Views/Lecturers/Update.cshtml
@using BLL.Models
@model Lecturer

<form asp-action="Update" asp-controller="Lecturers" asp-antiforgery="true">
    <div>
        <input asp-for="Id" type="hidden" />
        <div>
            <label asp-for="FirstName"></label>
            <input type="text" asp-for="FirstName" />
        </div>
        <div>
            <label asp-for="LastName"></label>
            <input type="text" asp-for="LastName" />
        </div>
        <div>
            <label asp-for="Position"></label>
            <input type="text" asp-for="Position" />
        </div>
        <div>
            <input type="submit" value="Save" />
        </div>
    </div>
</form>

ClassAttendance/src/WebUI/Views/Lecturers/_Lecturer.cshtml
@using BLL.Models
@model Lecturer

<div class="card card-body bg-dark my-auto text-light" style="width: 60%">
    <h4>@($"{Model.FirstName} {Model.LastName}")</h4>
    <h3>@Model.Position</h3>

    <form asp-action="Update" asp-controller="Lecturers" asp-route-id="@Model.Id" method="get">
        <button type="submit" class="btn btn-success">
            Update lecturer
        </button>
    </form>

    <form asp-action="Delete" asp-controller="Lecturers" asp-route-id="@Model.Id" method="get">
        <button type="submit" class="btn btn-danger">
            Delete lecturer
        </button>
    </form>

    <form asp-action="Lecturer" asp-controller="MissedClasses" asp-route-id="@Model.Id" method="get">
        <button type="submit" class="btn btn-primary">
            Get missed lectures
        </button>
    </form>

</div>