ClassAttendance/src/WebUI/Models/ViewModels/StudentModel/StudentViewModel.cs
namespace WebUI.Models.ViewModels.StudentModel
{
    public class StudentViewModel
    {
        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Address { get; set; }

        public string GroupName { get; set; }
    }
}

ClassAttendance/src/WebUI/Models/ViewModels/StudentViewModel.cs
namespace WebUI.Models.ViewModels
{
    public class StudentViewModel
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Address { get; set; }

        public string GroupName { get; set; }
    }
}

ClassAttendance/src/WebUI/Models/ViewModels/Students/StudentManageViewModel.cs
using BLL.Models;
using System.Collections.Generic;

namespace WebUI.Models.ViewModels.Students
{
    public class StudentManageViewModel
    {
        public Student Student { get; set; }

        public IEnumerable<Group> Groups { get; set; }
    }
}

ClassAttendance/src/WebUI/Models/ViewModels/Students/StudentViewModel.cs
namespace WebUI.Models.ViewModels.Students
{
    public class StudentViewModel
    {
        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Address { get; set; }

        public string GroupName { get; set; }
    }
}

ClassAttendance/src/WebUI/Controllers/MissedClassesController.cs
using BLL.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WebUI.Models.ViewModels.MissedClass;
using WebUI.Facades;
using WebUI.Models;
using Microsoft.Extensions.Logging;
using BLL.Exceptions;
using Microsoft.AspNetCore.Authorization;
using WebUI.Identity;
using WebUI.Extensions;

namespace WebUI.Controllers
{
    [Authorize(Roles = Roles.Manager)]
    public class MissedClassesController : Controller
    {
        private readonly MissedClassesFacade _missedClassesFacade;
        private readonly ILogger<MissedClassesController> _logger;

        public MissedClassesController(MissedClassesFacade missedClassesFacade, ILogger<MissedClassesController> logger)
        {
            _missedClassesFacade = missedClassesFacade;
            _logger = logger;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var models = await _missedClassesFacade.GetMissedLecturesAsync();
            _logger.LogInformation("Fetched lecturers");

            return View(models);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var lecturer = await _missedClassesFacade.GetManageViewModelAsync();

            return View(lecturer);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Add(MissedClassManageViewModel model)
        {
            if (ModelState.IsValid)
            {
                var missedClass = new MissedClass
                {
                    ClassId = model.ClassId,
                    StudentId = model.StudentId,
                };

                try
                {
                    await _missedClassesFacade.AddAsync(missedClass);
                    _logger.LogInformation("Added new missed class");

                    return RedirectToAction(nameof(List));

                }
                catch (BusinessLogicException ex)
                {
                    _logger.LogError(ex.Message);
                    var error = new ErrorViewModel
                    {
                        ErrorMessage = ex.Message,
                        ReturnUrl = Request.GetReferer(),
                    };

                    return View("Error", error);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var item = await _missedClassesFacade.GetManageViewModelAsync(id);

            return View(item);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(MissedClassManageViewModel model)
        {
            if (ModelState.IsValid)
            {
                var missedClass = new MissedClass
                {
                    ClassId = model.ClassId,
                    StudentId = model.StudentId,
                };

                try
                {
                    await _missedClassesFacade.UpdateAsync(missedClass);
                    _logger.LogInformation("Updated missed class");

                    return RedirectToAction(nameof(List));

                }
                catch (BusinessLogicException ex)
                {
                    _logger.LogError(ex.Message);
                    var error = new ErrorViewModel
                    {
                        ErrorMessage = ex.Message,
                        ReturnUrl = Request.GetReferer(),
                    };

                    return View("Error", error);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _missedClassesFacade.DeleteAsync(id);
                _logger.LogInformation("Deleted missed class");

                return RedirectToAction(nameof(List));

            }
            catch (BusinessLogicException ex)
            {
                _logger.LogError(ex.Message);
                var error = new ErrorViewModel
                {
                    ErrorMessage = ex.Message,
                    ReturnUrl = Request.GetReferer(),
                };

                return View("Error", error);
            }
        }

        [Authorize(Roles = Roles.UserAndManager)]
        [HttpGet]
        public async Task<IActionResult> Student(int id)
        {
            try
            {
                var viewModels = await _missedClassesFacade.GetStudentMissedClassesAsync(id);
                _logger.LogInformation("Fetched students's missed classes");

                return View(nameof(List), viewModels);
            }
            catch (BusinessLogicException ex)
            {
                _logger.LogError(ex.Message);
                var error = new ErrorViewModel
                {
                    ErrorMessage = ex.Message,
                    ReturnUrl = Request.GetReferer(),
                };

                return View("Error", error);
            }
        }

        [Authorize(Roles = Roles.UserAndManager)]
        [HttpGet]
        public async Task<IActionResult> Lecturer(int id)
        {
            try
            {
                var viewModels = await _missedClassesFacade.GetLecturerMissedClassesAsync(id);
                _logger.LogInformation("Fetched lecturer's missed classes");

                return View(nameof(List), viewModels);
            }
            catch (BusinessLogicException ex)
            {
                _logger.LogError(ex.Message);
                var error = new ErrorViewModel
                {
                    ErrorMessage = ex.Message,
                    ReturnUrl = Request.GetReferer(),
                };

                return View("Error", error);
            }
        }
    }
}

ClassAttendance/src/WebUI/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WebUI.Models.ViewModels.StudentModel;
using WebUI.Facades;
using Microsoft.Extensions.Logging;
using WebUI.Models;
using BLL.Exceptions;
using Microsoft.AspNetCore.Authorization;
using WebUI.Identity;
using WebUI.Extensions;

namespace WebUI.Controllers
{
    [Authorize(Roles = Roles.Manager)]
    public class StudentsController : Controller
    {
        private readonly StudentsFacade _studentsFacade;
        private readonly ILogger<StudentsController> _logger;

        public StudentsController(StudentsFacade studentsFacade, ILogger<StudentsController> logger)
        {
            _studentsFacade = studentsFacade;
            _logger = logger;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var studentList = await _studentsFacade.GetStudentListAsync();
            _logger.LogInformation("Fetched students");

            return View(studentList);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = await  _studentsFacade.GetViewModel();

            return View(model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Add(StudentManageViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _studentsFacade.AddStudentAsync(model.Student);
                    _logger.LogInformation("Added student");

                    return RedirectToAction(nameof(List));
                }
                catch (BusinessLogicException ex)
                {
                    _logger.LogError(ex.Message);
                    var error = new ErrorViewModel
                    {
                        ErrorMessage = ex.Message,
                        ReturnUrl = Request.GetReferer(),
                    };

                    return View("Error", error);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var model = await _studentsFacade.GetViewModel(id);

            return View(model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(StudentManageViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _studentsFacade.EditStudentAsync(model.Student);
                    _logger.LogInformation("Updated student");

                    return RedirectToAction(nameof(List));
                }
                catch (BusinessLogicException ex)
                {
                    _logger.LogError(ex.Message);
                    var error = new ErrorViewModel
                    {
                        ErrorMessage = ex.Message,
                        ReturnUrl = Request.GetReferer(),
                    };

                    return View("Error", error);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _studentsFacade.DeleteStudentAsync(id);
                _logger.LogInformation("Deleted student");

                return RedirectToAction(nameof(List));
            }
            catch (BusinessLogicException ex)
            {
                _logger.LogError(ex.Message);
                var error = new ErrorViewModel
                {
                    ErrorMessage = ex.Message,
                    ReturnUrl = Request.GetReferer(),
                };

                return View("Error", error);
            }
        }
    }
}

ClassAttendance/src/WebUI/Views/Students/Add.cshtml
@using WebUI.Models.ViewModels.StudentModel
@using BLL.Models
@model StudentManageViewModel

<form asp-action="Add" asp-controller="Students" asp-antiforgery="true">
    <div>
        <div>
            <label asp-for="Student.FirstName"></label>
            <input type="text" asp-for="Student.FirstName" />
        </div>
        <div>
            <label asp-for="Student.LastName"></label>
            <input type="text" asp-for="Student.LastName" />
        </div>
        <div>
            <label asp-for="Student.Address"></label>
            <input type="text" asp-for="Student.Address" />
        </div>
        <div>
            <label asp-for="Student.GroupId"></label>
            <select asp-for="@Model.Student.GroupId" asp-items="@(new SelectList(Model.Groups, nameof(Group.Id), nameof(Group.Name)))"></select>
        </div>
        <div>
            <input type="submit" value="Save" />
        </div>
    </div>
</form>

ClassAttendance/src/WebUI/Views/Students/List.cshtml
@using WebUI.Models.ViewModels.StudentModel
@model IEnumerable<StudentViewModel>

@foreach (var model in Model)
{
    @await Html.PartialAsync("_Student", model)
}

ClassAttendance/src/WebUI/Views/Students/Update.cshtml
@using WebUI.Models.ViewModels.StudentModel
@using BLL.Models
@model StudentManageViewModel

<form asp-action="Update" asp-controller="Students" asp-antiforgery="true">
    <div>
        <input type="hidden" asp-for="Student.Id" />
        <div>
            <label asp-for="Student.FirstName"></label>
            <input type="text" asp-for="Student.FirstName" />
        </div>
        <div>
            <label asp-for="Student.LastName"></label>
            <input type="text" asp-for="Student.LastName" />
        </div>
        <div>
            <label asp-for="Student.Address"></label>
            <input type="text" asp-for="Student.Address" />
        </div>
        <div>
            <label asp-for="Student.GroupId"></label>
            <select asp-for="@Model.Student.GroupId" asp-items="@(new SelectList(Model.Groups, nameof(Group.Id), nameof(Group.Name)))"></select>
        </div>
        <div>
            <input type="submit" value="Save" />
        </div>
    </div>
</form>

ClassAttendance/src/WebUI/Views/Students/_Student.cshtml
@using WebUI.Models.ViewModels.StudentModel
@model StudentViewModel

<div class="card card-body bg-dark my-auto text-light" style="width: 60%">
    <h4>@($"{Model.FirstName} {Model.LastName}")</h4>
    <h3>@Model.Address</h3>
    <h3>@Model.GroupName</h3>

    <form asp-action="Update" asp-controller="Students" asp-route-id="@Model.Id" method="get">
        <button type="submit" class="btn btn-success">
            Update student
        </button>
    </form>

    <form asp-action="Delete" asp-controller="Students" asp-route-id="@Model.Id" method="get">
        <button type="submit" class="btn btn-danger">
            Delete student
        </button>
    </form>

    <form asp-action="Student" asp-controller="MissedClasses" asp-route-id="@Model.Id" method="get">
        <button type="submit" class="btn btn-primary">
            Get missed lectures
        </button>
    </form>

</div>